name: pwa

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: './package.json'
          cache: 'pnpm'            # ← pnpm の依存キャッシュも有効に

      # ★ pnpm をインストール
      - uses: pnpm/action-setup@v3
        with:
          version: 9               # 使いたいバージョン
          run_install: false       # ここでは install しない

      - run: pnpm install          # 以降は普通に pnpm コマンドが使える
      - run: pnpm test
      - run: pnpm build

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
