name: pwa

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node を入れる（キャッシュ設定は外す）
      - uses: actions/setup-node@v4
        with:
          node-version-file: './package.json'  # Volta の pin を参照

      # pnpm をインストール ＆ キャッシュ
      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false
          cache: true               # ← ここで pnpm-lock.yaml キャッシュ管理

      - run: pnpm install --frozen-lockfile
      - run: pnpm test
      - run: pnpm build

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
